### ISSUE TITLE
Building error: duplicate symbol '__associated_object_key'

### ISSUE THREAD

**Issue by Mx-Iris** [p-x9/AssociatedObject#34]
I used the library in both libraries and the compilation reported an error, maybe due to @_exported import AssociatedObjectC? , because the duplicate symbols come from here

```
duplicate symbol '__associated_object_key' in:
ld: 1 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)

1 duplicate symbols

Linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by p-x9** [comment]
Hello.
Are you using this with CocoaPods?

**Comment by Mx-Iris** [comment]
> Hello. Are you using this with CocoaPods?

I using SwiftPM

This does not seem to be a problem caused by references from multiple libraries. I encountered this issue when I added an associated object in an extension of NSView and then added another associated object in an extension of NSControl. NSControl inherits from NSView.

**Comment by p-x9** [comment]
Thanks.
I have tried it and it seems to work fine for me.

Maybe a clean build will get it to work.

**Comment by Mx-Iris** [comment]
> Thanks. 谢谢。 I have tried it and it seems to work fine for me.我已经尝试过了，对我来说似乎运行良好。
> 
> Maybe a clean build will get it to work.或许重新编译能使它工作。

[MyLibrary.zip](https://github.com/p-x9/AssociatedObject/files/14399653/MyLibrary.zip)
This is an example that can be replicated by importing the library in two different files

**Comment by p-x9** [comment]
Thanks. It certainly did not work. Sorry.

It was probably because I had implemented the _associated_object_key function in the header file.
