### ISSUE TITLE
There may be a problem when other third-party framework use `get_return_address()`....

### ISSUE THREAD

**Issue by mlch911** [p-x9/AssociatedObject#39]
I found the associated object will become nil after some time in `Release` mode. I definitely did not set it.

I can only assume there may be some other third-party framework which uses `get_return_address()` as their key as well. 🤣

**Comment by p-x9** [comment]
`get_return_address` is actually a C macro that uses the `__builtin_return_address` function to obtain the return address of the function that called it.

https://github.com/p-x9/AssociatedObject/blob/18f87a7cb2b13145daf2a46f4cbacd59b63fc976/Sources/AssociatedObjectC/include/associated_object_key.h#L16

The AssociatedObject macro creates the following function that wraps this and generates a unique key.

```swift
@inline(never) 
static var __associated_intKey: UnsafeRawPointer {
  _associated_object_key()
}
```

If the function is expanded inline in a release build, the index passed to __builtin_return_address may be misaligned and uniqueness may not be preserved.
I had set up an attribute to prevent this from happening, but it may not be working properly.

If the problem occurs only in RELEASE builds, then this is the most likely cause.
However, if the problem also occurs in DEBUG builds, it is possible that the policy settings are incorrect.

**Comment by mlch911** [comment]
> `get_return_address` is actually a C macro that uses the `__builtin_return_address` function to obtain the return address of the function that called it. `get_return_address` 实际上是一个 C 宏，它使用该 `__builtin_return_address` 函数来获取调用它的函数的返回地址。
> 
> https://github.com/p-x9/AssociatedObject/blob/18f87a7cb2b13145daf2a46f4cbacd59b63fc976/Sources/AssociatedObjectC/include/associated_object_key.h#L16
> 
> The AssociatedObject macro creates the following function that wraps this and generates a unique key.AssociatedObject 宏创建以下函数来包装此函数并生成唯一键。
> 
> ```swift
> @inline(never) 
> static var __associated_intKey: UnsafeRawPointer {
>   _associated_object_key()
> }
> ```
> 
> If the function is expanded inline in a release build, the index passed to __builtin_return_address may be misaligned and uniqueness may not be preserved.如果函数在发布版本中以内联方式扩展，则传递给__builtin_return_address的索引可能会未对齐，并且可能无法保留唯一性。 I had set up an attribute to prevent this from happening, but it may not be working properly.我设置了一个属性来防止这种情况发生，但它可能无法正常工作。
> 
> If the problem occurs only in RELEASE builds, then this is the most likely cause.如果问题仅在 RELEASE 版本中出现，则这是最可能的原因。 However, if the problem also occurs in DEBUG builds, it is possible that the policy settings are incorrect.但是，如果 DEBUG 版本中也出现此问题，则可能是策略设置不正确。

It only occurs in RELEASE build.

**Comment by p-x9** [comment]
Fixed Key generation method.

https://github.com/p-x9/AssociatedObject/releases/tag/0.10.3
